### ISSUE TITLE
Always error 503 for every instance

### ISSUE THREAD

**Issue by incrediblyimpressiveusername** [zyachel/quetre#142]
No instance of Quetre works for me. I invariably get the "503 Quora is rate limiting this instance. Try another or host your own."-error. And this has been the case without exception since at least October 2023, possibly even longer (that's merely the earliest I am certain of).

Until today, I had blindly assumed that this experience was universally shared, and never followed up the matter. But it turns out that I was mistaken and others have been and are currently able to use Quetre just fine.

Which then begs the question, what is causing the error to trigger for me without fail regardless of instance? And is there any trick to avoid it, or some way around it?

**Comment by shindouj** [comment]
It looks like my instance is *now* affected as well. I have just tried visiting [this Quora link](https://quetre.jeikobu.net/What-is-the-difference-between-a-PLD-and-an-FPGA) on my instance, and it is rate limited. I have tried HTTP proxying it through Cloudflare WARP to no avail. 

This might be a change on Quora's side.

**Comment by Victor239** [comment]
Can confirm this fails with a new instance on a different IP.

**Comment by dave0003** [comment]
I set up 8 rotating IPs on my quetre instance (q.307200.xyz), but they were all getting rate limited within 24 hours.

I went through the instance list, and most aren't working (some even behind proof-of-work captchas).

These were the only ones I could get to work:

https://q.opnxng.com/ 	No 	No 	SG 	Vultr 	Operated by Opnxng
https://quetre.ducks.party/ 	No 	No 	NL 	Timeweb 	Operated by ducks.party
https://quetre.canine.tools/ 	No 	No 	US 	RoyaleHosting 	Operated by canine.tools
https://quetre.jeikobu.net 	No 	No 	DE 	Hetzner (Cloudflare) 	Operated by Shindou Jeikobu
https://quetre.franklyflawless.org 	No 	No 	DE 	Hetzner 	Operated by FranklyFlawless
https://quetre.privacyredirect.com/ 	No 	No 	FI 	Private WebHost 	Operated by privacyredirect
https://quora.nerdvpn.de 	No 	No 	UA 	Virtual Systems LLC 	Operated by Weidenwiesel. Uses Anubis to protect against AI and Bots. Routed over rotating proxies.

**Comment by shindouj** [comment]
@dave0003 I have managed to make mine work by proxying it through CF Warp and setting Anubis in front of it. Otherwise bots would just cause it to rate limit after a while. Quetre respects the PROXY environment variable, so it is fairly easy to set it up.

Here's my Swarm-friendly Compose:

```yaml
services:
  anubis:
    image: ghcr.io/techarohq/anubis:main
    networks:
      - caddy-swarm
      - default
    restart: always
    environment:
      TARGET: "http://app:3000"
      REDIRECT_DOMAINS: "quetre.jeikobu.net"
      COOKIE_DOMAIN: "jeikobu.net"
      ED25519_PRIVATE_KEY_HEX: "<snip>"
    labels:
      caddy: "quetre.jeikobu.net"
      caddy.0_route.crowdsec: ""
      caddy.log.output: "discard"
      caddy.reverse_proxy: "{{ upstreams 8923 }}"
      caddy.reverse_proxy.0_header_up: "X-Forwarded-For {client_ip}"
      caddy.reverse_proxy.1_header_up: "X-Real-IP {client_ip}"
      caddy.reverse_proxy.2_header_up: "X-Http-Version {http.request.proto}"
      
  app:
    image: ghcr.io/shindouj/quetre:latest
    restart: unless-stopped
    environment:
      - "NODE_ENV=production"
      - "PORT=3000"
      - "CACHE_PERIOD=1h"
      - "REDIS_URL=redis:6379"
      - "REDIS_TTL=3600"
      - "PROXY=http://warp:1080"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    networks:
      - default
      - warp-swarm
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:3000 || exit 1
      interval: 1m
      timeout: 3s
    depends_on:
      - redis
      - warp-launcher
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        failure_action: rollback
        order: start-first
        monitor: 5m
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 60s

  warp-launcher:
    image: ixdotai/swarm-launcher
    environment:
      LAUNCH_IMAGE: "caomingjun/warp"
      LAUNCH_PROJECT_NAME: "quetre"
      LAUNCH_SERVICE_NAME: "warp"
      LAUNCH_CONTAINER_NAME: "warp"
      LAUNCH_EXT_NETWORKS: "warp-swarm"
      LAUNCH_CAP_ADD: "NET_ADMIN"
      LAUNCH_PULL: "true"
      LAUNCH_DEVICES: "/dev/net/tun:/dev/net/tun"
      LAUNCH_VOLUMES: "./data:/var/lib/cloudflare-warp"
      LAUNCH_ENVIRONMENTS: "WARP_SLEEP=2"
      LAUNCH_SYSCTLS: "net.ipv6.conf.all.disable_ipv6=0 net.ipv4.conf.all.src_valid_mark=1"
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:rw'
    networks:
      - warp-swarm
        
  redis:
    image: docker.io/redis:alpine
    restart: unless-stopped
    healthcheck:
      test: redis-cli ping
      interval: 30s
      timeout: 5s
      retries: 2
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        failure_action: rollback
        order: start-first
        monitor: 5m
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 60s
      
networks:
  caddy-swarm:
    external: true
  warp-swarm:
    attachable: true
    driver: overlay
```
